#!/usr/bin/env bash

set -euo pipefail
(exec bwrap \
	--unshare-all \
	--share-net \
	--die-with-parent \
	--clearenv \
	--setenv "HOME" "/home/nm" \
	--setenv "USER" "/home/nm" \
	--setenv "LOGNAME" "/home/nm" \
	--setenv "PATH" "/usr/bin" \
	--setenv "TERM" "$TERM" \
	--hostname "nat" \
	--dev "/dev" \
	--proc "/proc" \
	--tmpfs "/tmp" \
	--ro-bind "/usr/share" "/usr/share" \
	--ro-bind "/usr/lib" "/lib" \
	--ro-bind "/usr/lib64" "/lib64" \
	--ro-bind "/usr/lib" "/usr/lib" \
	--ro-bind "/usr/lib64" "/usr/lib64" \
	--ro-bind "/usr/bin" "/usr/bin" \
	--ro-bind "/usr/share" "/usr/share" \
	--ro-bind "/etc/fonts" "/etc/fonts" \
	--ro-bind "/etc/resolv.conf" "/etc/resolv.conf" \
	--ro-bind "/etc/ssl" "/etc/ssl" \
	--ro-bind "/etc/ca-certificates" "/etc/ca-certificates" \
	--ro-bind "/etc/localtime" "/etc/localtime" \
	--ro-bind "/etc/containers/seccomp.json" "/etc/containers/seccomp.json" \
	--ro-bind "$HOME/.bwrap/codbox/etc/hosts" "/etc/hosts" \
	--ro-bind "$HOME/.bwrap/codbox/etc/resolv.conf" "/etc/resolv.conf" \
	--ro-bind "$HOME/.bwrap/codbox/etc/proxychains.conf" "/etc/proxychains.conf" \
	--ro-bind "$HOME/.bwrap/codbox/etc/environment" "/etc/environment" \
	--ro-bind "$HOME/.bwrap/codbox/etc/machine-id" "/etc/machine-id" \
	--ro-bind "$HOME/.bwrap/codbox/etc/machine-id" "/var/lib/dbus/machine-id" \
	--ro-bind "$HOME/.bwrap/codbox/usr/local" "/usr/local" \
	--bind-try "$HOME/gt/test" "/home/nm/build/" \
	--bind-try "$HOME/.bwrap/codbox/.tircx" "/home/nm/.tircx" \
	--bind-try "$HOME/.bwrap/codbox/.gitconfig" "/home/nm/.gitconfig" \
	--bind-try "$HOME/.bwrap/codbox/.curlrc" "/home/nm/.curlrc" \
	--bind-try "$HOME/.bwrap/codbox/.config/lazy" "/home/nm/.config/lazy" \
	--bind-try "$HOME/.bwrap/codbox/.config/nvim" "/home/nm/.config/nvim" \
	--bind-try "$HOME/.bwrap/codbox/.config/github-copilot" "/home/nm/.config/github-copilot" \
	--bind-try "$HOME/.bwrap/codbox/.neovim-ghq" "/home/nm/.neovim-ghq" \
	--bind-try "$HOME/.bwrap/codbox/.config/yarn/lsp" "/home/nm/.config/yarn/lsp" \
	--bind-try "$HOME/.bwrap/codbox/.config/fish" "/home/nm/.config/fish" \
	--bind-try "$HOME/.bwrap/codbox/.config/zellij" "/home/nm/.config/zellij" \
	--bind-try "$HOME/.bwrap/codbox/.local" "/home/nm/.local" \
	--bind-try "$HOME/.bwrap/codbox/.cache" "/home/nm/.cache" \
	--bind-try "$HOME/.bwrap/codbox/.cargo" "/home/nm/.cargo" \
	--bind-try "$HOME/.bwrap/codbox/.rustup" "/home/nm/.rustup" \
/usr/bin/fish -c "zellij attach onetree") \
11< <(getent passwd $UID 651112) \
12< <(getent group $(id -g) 532328) \


 
#	--tmpfs "/usr/lib/modules" \
#	--tmpfs "/usr/lib/systemd" \
