# Jump
alias box "cd $HOME/build/debox"

alias nvimEdit "cd $HOME/.config/nvim/"
alias user "cd $HOME/build/blox/user/"
alias dot "cd $HOME/build/dot/"
alias three-home-git "cd $HOME/build/gt/three-home"
alias w2b3-git "cd $HOME/build/gt/w2b3"
alias icnote-git "cd $HOME/build/gt/icnote"
alias mind-git "cd $HOME/build/gt/mindnote"
alias maptest-git "cd $HOME/build/gt/Mindest"
alias home-git "cd $HOME/build/gt/homepage"
alias day-git "cd $HOME/build/daybyday"
alias dayPost "cd $HOME/build/gt/daybyday/src/pages/posts/"
alias stapler-git "cd $HOME/build/gt/stapler"
alias testDay "cd $HOME/build/gt/testDay"
alias ppt "cd $HOME/build/gt/ppt-work-test"
alias blog "cd $HOME/build/blox/"
alias fwork "cd $HOME/build/firefox-extensions-test/vimfox"
alias ImGallery "cd $HOME/build/gt/Im-Gallery/"
alias fworklook "cd $HOME/build/project/extensions/"
alias box "cd $HOME/build/debox"
alias chattest "cd $HOME/build/blox/project/pages/chatvala"
alias pro "cd $HOME/build/blox/pro/"
alias autoGPT "cd $HOME/build/blox/pro/autoGPT"
alias ot-git "cd $HOME/build/gt/ot-champion"


alias http "python -m http.server 9981"

alias fishEdit "vim $HOME/.config/fish/config.fish"
