#!/bin/sh

export TERM=foot
export DISPLAY=":0"
export XKB_DEFAULT_OPTIONS=caps:swapescape,ctrl:swap_lalt_lctl_lwin,ctrl:swap_rwin_rctl,ctrl:menu_rctrl,ctrl:ralt_rctrl
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND="wayland"
export QT_QPA_PLATFORM="wayland"
export XDG_SESSION_TYPE="wayland"
export XDG_CURRENT_DESKTOP="sway"

exec dbus-run-session sway
