#!/usr/bin/env bash
set -euo pipefail
(
  exec bwrap \
    --unshare-all \
    --share-net \
    --clearenv \
    --setenv HOME /home/ff \
    --setenv GTK_THEME Adwaita:light \
    --setenv MOZ_ENABLE_WAYLAND 1 \
    --setenv WAYLAND_DISPLAY "$WAYLAND_DISPLAY" \
    --setenv XDG_RUNTIME_DIR "$XDG_RUNTIME_DIR" \
    --setenv LANG "$LANG" \
    --setenv PATH /usr/bin \
    --unsetenv DBUS_SESSION_BUS_ADDRESS \
    --hostname fs \
    --ro-bind /usr/lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/bin/sh /usr/bin/sh \
    --ro-bind-try /etc/fonts /etc/fonts \
    --ro-bind-try /etc/resolv.conf /etc/resolv.conf \
    --ro-bind-try /sys/bus/pci /sys/bus/pci \
    --ro-bind-try /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
    --ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
    --ro-bind /usr/share/fonts /usr/share/fonts \
    --ro-bind /usr/share/glvnd /usr/share/glvnd \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
    --ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" \
    --ro-bind /run/user/"$(id -u)"/bus /run/user/"$(id -u)"/bus \
    --ro-bind "$HOME"/.bwrap/fbox/.config/dconf/user /home/ff/.config/dconf/user \
    --dev-bind /dev/dri /dev/dri \
    --dev /dev \
    --proc /proc \
    --tmpfs /tmp \
    --ro-bind "$HOME"/.bwrap/fbox/machine-id /etc/machine-id \
    --ro-bind "$HOME"/.bwrap/fbox/machine-id /var/lib/dbus/machine-id \
    --ro-bind "$HOME"/.bwrap/fbox/etc/hosts /etc/hosts \
    --bind-try "$HOME"/.bwrap/fbox/run/user/"$(id -u)"/dconf/user /run/user/"$(id -u)"/dconf/user \
    --bind-try "$HOME"/.bwrap/fbox/.mozilla /home/ff/.mozilla \
    --bind-try "$HOME"/.bwrap/fbox/.cache/ /home/ff/.cache \
    --die-with-parent \
    --new-session \
    --uid 218 --gid 136 \
    /usr/lib/firefox/firefox --no-remote -P
)

#    --ro-bind /usr/share/libdrm /usr/share/libdrm \
#    --ro-bind /usr/share/applications /usr/share/applications \
