#!/usr/bin/env bash

set -euo pipefail
(exec bwrap \
  --unshare-all \
  --share-net \
  --clearenv \
  --setenv "PATH" "/usr/bin" \
  --setenv "HOME" "/home/cod1ng" \
  --setenv "USER" "/home/cod1ng" \
  --setenv "LOGNAME" "/home/cod1ng" \
  --setenv "TERM" "$TERM" \
  --hostname "nsiu123" \
  --symlink "/usr/bin" "/bin" \
  --symlink "/usr/bin" "/sbin" \
  --symlink "/usr/lib" "/lib" \
  --ro-bind "/usr/lib" "/usr/lib" \
  --ro-bind "/usr/share" "/usr/share" \
  --ro-bind "/usr/bin" "/usr/bin" \
  --ro-bind "/usr/lib64/ld-linux-x86-64.so.2" "/lib64/ld-linux-x86-64.so.2" \
  --ro-bind "/etc/fonts" "/etc/fonts" \
  --ro-bind "/etc/resolv.conf" "/etc/resolv.conf" \
  --ro-bind "/etc/ssl" "/etc/ssl" \
  --ro-bind "/etc/ca-certificates" "/etc/ca-certificates" \
  --ro-bind "/etc/localtime" "/etc/localtime" \
  --ro-bind "/etc/containers/seccomp.json" "/etc/containers/seccomp.json" \
  --ro-bind "$HOME/.bwrap/.codeBox/etc/hosts" "/etc/hosts" \
  --ro-bind "$HOME/.bwrap/.codeBox/etc/resolv.conf" "/etc/resolv.conf" \
  --ro-bind "$HOME/.bwrap/.codeBox/etc/environment" "/etc/environment" \
  --ro-bind "$HOME/.bwrap/.codeBox/machine-id" "/etc/machine-id" \
  --ro-bind "$HOME/.bwrap/.codeBox/machine-id" "/var/lib/dbus/machine-id" \
  --proc "/proc" \
  --dev "/dev" \
  --tmpfs "/tmp" \
  --bind-try "$HOME/github" "/home/cod1ng/build/github" \
  --bind-try "$HOME/.bwrap/.codeBox/.tircx" "/home/cod1ng/.tircx" \
  --bind-try "$HOME/.bwrap/.codeBox/.deno" "/home/cod1ng/.deno" \
  --bind-try "$HOME/.bwrap/.codeBox/.gitconfig" "/home/cod1ng/.gitconfig" \
  --bind-try "$HOME/.bwrap/.codeBox/.curlrc" "/home/cod1ng/.curlrc" \
  --bind-try "$HOME/.bwrap/.codeBox/.tmux.conf" "/home/cod1ng/.tmux.conf" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/tmux" "/home/cod1ng/.config/tmux" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/lazy" "/home/cod1ng/.config/lazy" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/github-copilot" "/home/cod1ng/.config/github-copilot" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/nvim" "/home/cod1ng/.config/nvim" \
  --bind-try "$HOME/check/dot/craftdog/.config/nvim" "/home/cod1ng/.config/test-vim/.cdog-demo" \
  --bind-try "$HOME/.bwrap/.codeBox/.neovim-ghq" "/home/cod1ng/.neovim-ghq" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/yarn/lsp" "/home/cod1ng/.config/yarn/lsp" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/yarn/sveltelsp" "/home/cod1ng/.config/yarn/sveltelsp" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/yarn/global" "/home/cod1ng/.config/yarn/global" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/yarn/bin" "/home/cod1ng/.config/yarn/bin" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/nushell" "/home/cod1ng/.config/nushell" \
  --bind-try "$HOME/.bwrap/.codeBox/.config/fish" "/home/cod1ng/.config/fish" \
  --bind-try "$HOME/.bwrap/.codeBox/.local" "/home/cod1ng/.local" \
  --bind-try "$HOME/.bwrap/.codeBox/.cache" "/home/cod1ng/.cache" \
  --bind-try "$HOME/.bwrap/.codeBox/usr/local" "/usr/local" \
/usr/bin/fish -c "tmux new-session -s codeTest01") \
11< <(getent passwd $UID 65522) \
12< <(getent group $(id -g) 55321) \

