#!/usr/bin/env bash

set -euo pipefail
(exec bwrap \
  --unshare-all \
  --share-net \
  --clearenv \
  --setenv "PATH" "/usr/bin" \
  --setenv "HOME" "/home/nsb" \
  --setenv "USER" "/home/nsb" \
  --setenv "LOGNAME" "/home/nsb" \
  --setenv "TERM" "$TERM" \
  --hostname "nat" \
  --symlink "/usr/bin" "/bin" \
  --symlink "/usr/bin" "/nsbin" \
  --symlink "/usr/lib" "/lib" \
  --ro-bind "/usr/lib" "/usr/lib" \
  --ro-bind "/usr/share" "/usr/share" \
  --ro-bind "/usr/bin" "/usr/bin" \
  --ro-bind "/usr/lib64/ld-linux-x86-64.so.2" "/lib64/ld-linux-x86-64.so.2" \
  --ro-bind "/etc/fonts" "/etc/fonts" \
  --ro-bind "/etc/resolv.conf" "/etc/resolv.conf" \
  --ro-bind "/etc/ssl" "/etc/ssl" \
  --ro-bind "/etc/ca-certificates" "/etc/ca-certificates" \
  --ro-bind "/etc/localtime" "/etc/localtime" \
  --ro-bind "/etc/containers/seccomp.json" "/etc/containers/seccomp.json" \
  --ro-bind "$HOME/.bwrap/codbox/etc/hosts" "/etc/hosts" \
  --ro-bind "$HOME/.bwrap/codbox/etc/resolv.conf" "/etc/resolv.conf" \
  --ro-bind "$HOME/.bwrap/codbox/etc/proxychains.conf" "/etc/proxychains.conf" \
  --ro-bind "$HOME/.bwrap/codbox/etc/environment" "/etc/environment" \
  --ro-bind "$HOME/.bwrap/codbox/etc/machine-id" "/etc/machine-id" \
  --ro-bind "$HOME/.bwrap/codbox/etc/machine-id" "/var/lib/dbus/machine-id" \
  --proc "/proc" \
  --dev "/dev" \
  --tmpfs "/tmp" \
  --bind-try "$HOME/gt/test" "/home/nsb/build/" \
  --bind-try "$HOME/.bwrap/codbox/.tircx" "/home/nsb/.tircx" \
  --bind-try "$HOME/.bwrap/codbox/.gitconfig" "/home/nsb/.gitconfig" \
  --bind-try "$HOME/.bwrap/codbox/.curlrc" "/home/nsb/.curlrc" \
  --bind-try "$HOME/.bwrap/codbox/.config/lazy" "/home/nsb/.config/lazy" \
  --bind-try "$HOME/.bwrap/codbox/.config/github-copilot" "/home/nsb/.config/github-copilot" \
  --bind-try "$HOME/.bwrap/codbox/.config/nvim" "/home/nsb/.config/nvim" \
  --bind-try "$HOME/.bwrap/codbox/.neovim-ghq" "/home/nsb/.neovim-ghq" \
  --bind-try "$HOME/.bwrap/codbox/.config/yarn/lsp" "/home/nsb/.config/yarn/lsp" \
  --bind-try "$HOME/.bwrap/codbox/.config/yarn/global" "/home/nsb/.config/yarn/global" \
  --bind-try "$HOME/.bwrap/codbox/.config/yarn/bin" "/home/nsb/.config/yarn/bin" \
  --bind-try "$HOME/.bwrap/codbox/.config/fish" "/home/nsb/.config/fish" \
  --bind-try "$HOME/.bwrap/codbox/.local" "/home/nsb/.local" \
  --bind-try "$HOME/.bwrap/codbox/.cache" "/home/nsb/.cache" \
  --bind-try "$HOME/.bwrap/codbox/usr/local" "/usr/local" \
/usr/bin/fish) \
11< <(getent passwd $UID 651112) \
12< <(getent group $(id -g) 532328) \

