#!/usr/bin/env bash

readonly V2RAY_CONFIG_DIR="$HOME/.bwrap/vbox/.config/v/"

cd $V2RAY_CONFIG_DIR  || exit 1
v2ray_deps=($(ldd /usr/bin/v2ray | awk '/=> \// {print $3}'))
set -euo pipefail
(exec bwrap \
    --ro-bind /usr/lib/libc.so.6 /usr/lib/libc.so.6 \
    --ro-bind /usr/lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 \
    --ro-bind /etc/v2ray/vpoint_socks_vmess.json /etc/v2ray/vpoint_socks_vmess.json \
    --ro-bind /etc/v2ray/vpoint_vmess_freedom.json /etc/v2ray/vpoint_vmess_freedom.json \
    --ro-bind /usr/lib/systemd/system/v2ray.service /usr/lib/systemd/system/v2ray.service \
    --ro-bind /usr/lib/systemd/system/"v2ray@.service" /usr/lib/systemd/system/"v2ray@.service" \
    --ro-bind /usr/share/v2ray/geosite.dat /usr/share/v2ray/geosite.dat \
    --ro-bind /usr/share/v2ray/geoip.dat /usr/share/v2ray/geoip.dat \
    --ro-bind $V2RAY_CONFIG_DIR/us-x1.json $HOME/.config/v2ray/config.json \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --ro-bind /etc/localtime /etc/localtime \
    --ro-bind /usr/bin/v2ray /usr/bin/v2ray \
    --hostname uubn108gb \
    --unshare-pid \
    --unshare-uts \
    --unshare-cgroup-try \
    --unshare-user \
    --unshare-ipc \
    --die-with-parent \
    --setenv PATH "/usr/bin" \
    /usr/bin/v2ray run --config $HOME/.config/v2ray/config.json
  )

