#!/usr/bin/env bash

cd $HOME/.config/v &&

set -euo pipefail
(exec bwrap \
    --ro-bind /usr/lib/libc.so.6 /usr/lib/libc.so.6 \
    --ro-bind /usr/lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 \
    --ro-bind /etc/v2ray/vpoint_socks_vmess.json /etc/v2ray/vpoint_socks_vmess.json \
    --ro-bind /etc/v2ray/vpoint_vmess_freedom.json /etc/v2ray/vpoint_vmess_freedom.json \
    --ro-bind /usr/lib/systemd/system/v2ray.service /usr/lib/systemd/system/v2ray.service \
    --ro-bind /usr/lib/systemd/system/"v2ray@.service" /usr/lib/systemd/system/"v2ray@.service" \
    --ro-bind /usr/share/v2ray/geosite.dat /usr/share/v2ray/geosite.dat \
    --ro-bind /usr/share/v2ray/geoip.dat /usr/share/v2ray/geoip.dat \
    --ro-bind $HOME/.bwrap/vbox/.config/v/config.json $HOME/.config/v/config.json \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --ro-bind /usr/bin/v2ray /usr/bin/v2ray \
    --hostname mt \
    --unshare-pid \
    --unshare-uts \
    --unshare-cgroup-try \
    --unshare-user \
    /usr/bin/v2ray run)

